//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHadelar
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersDetail
    {
        public int Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Email { get; set; }
        public string Address { get; set; }
        public string Contact_Number { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Gender { get; set; }
    }
}
