//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHadelar
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineDetail
    {
        public int Invoice_No { get; set; }
        public int Product_Id { get; set; }
        public int Qntity { get; set; }
        public decimal Unit_Price { get; set; }
        public decimal Total_Price { get; set; }
    }
}
